module.exports = {
  ROLES: {
    ADMIN: 'Admin',
    DOCTOR: 'Doctor',
    RECEPTIONIST: 'Receptionist',
    PHARMACIST: 'Pharmacist',
    LAB_TECH: 'LabTech',
    PATIENT: 'Patient',
  },

  APPOINTMENT_STATUS: {
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    CHECKED_IN: 'CHECKED_IN',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    NO_SHOW: 'NO_SHOW',
  },

  PRESCRIPTION_STATUS: {
    DRAFT: 'DRAFT',
    APPROVED: 'APPROVED',
    DISPENSED: 'DISPENSED',
    INVOICED: 'INVOICED',
    READY_FOR_DISPENSE: 'READY_FOR_DISPENSE',
  },

  INVOICE_STATUS: {
    UNPAID: 'UNPAID',
    PAID: 'PAID',
    REFUNDED: 'REFUNDED',
  },

  LAB_STATUS: {
    PENDING: 'PENDING',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
  },

  NOTIFICATION_TYPES: {
    APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
    APPOINTMENT_CONFIRMED: 'APPOINTMENT_CONFIRMED',
    APPOINTMENT_REMINDER: 'APPOINTMENT_REMINDER',
    APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
    PATIENT_CHECKED_IN: 'PATIENT_CHECKED_IN',
    PRESCRIPTION_READY: 'PRESCRIPTION_READY',
    LAB_RESULT_READY: 'LAB_RESULT_READY',
    LOW_STOCK: 'LOW_STOCK',
    EXPIRING_MEDICINES: 'EXPIRING_MEDICINES',
    HIGH_RISK_ALERT: 'HIGH_RISK_ALERT',
  },

  FILE_UPLOAD: {
    MAX_SIZE: parseInt(process.env.MAX_FILE_SIZE) || 5 * 1024 * 1024, // 5MB
    ALLOWED_TYPES: process.env.ALLOWED_FILE_TYPES?.split(',') || ['jpg', 'jpeg', 'png', 'pdf'],
  },

  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 10,
    MAX_LIMIT: 100,
  },

  TIMESLOT: {
    DEFAULT_DURATION: 20, // minutes
    MAX_PATIENTS: 1,
  },

  STOCK_ALERTS: {
    LOW_STOCK_THRESHOLD: 20,
    EXPIRY_WARNING_DAYS: 30,
  },
};